[PHP]
extension_dir = "C:\Program Files\php-8.5\ext"
extension=pdo_mysql
extension=pdo_sqlite
extension=mbstring
extension=openssl
extension=curl
extension=fileinfo

display_errors = On
display_startup_errors = On
error_reporting = E_ALL
